### ISSUE TITLE
Velib defectueux (tps)

### ISSUE THREAD

**Issue by Mankouri** [lhoang/velib#1]
Date : 22/10/2019
`{"BIKEID":"33233","DISTANCE":"1.0","SAVED_CARBON_DIOXIDE":0.1},"startDate":1571741912000,"endDate":1571747409000,"operationDate":1571741912000,"subscriptionDate":1568363838000,"offerCode":"V1_OFFRE_LD_V_MAX_TARIF_NORMAL_M","walletId":960921},{"code":"26_V1_CHARGE_USAGE","description":"La charge d\u0027usage","userAccount":"94621565680566764","walletTemplate":"PRINCIPAL","seller":"VELIB","chargeInstance":"26_V1_CHARGE_USAGE","chargeInstanceId":9635241,"currency":"EUR","status":"TREATED","ratingUnitDescription":"second","taxPercent":20,"unitAmountWithoutTax":0,"unitAmountWithTax":0,"unitAmountTax":0,"quantity":394,"amountWithoutTax":0,"amountWithTax":0,"amountTax":0,"parameter1":"yes","parameter2":"TRAJET_USAGE","parameter3":`

**Comment by lhoang** [comment]
fixed
